In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
all_df = pd.read_csv("total_stats.csv")

all_df.head()

,Unnamed: 0,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,...,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals,W,Season
0,0,GSW,2402,612,2877,6981,0.503,3509,1668,0.815,...,2370,0.391,926,3568,1267,4611,0.560,2583,58,2017-2018
1,1,HOU,1767,392,2825,6906,0.460,3174,2061,0.781,...,3470,0.362,1256,3564,1135,3436,0.558,1918,65,2017-2018
2,2,NOP,2195,485,2924,7241,0.483,3500,1716,0.772,...,2312,0.362,837,3636,1223,4929,0.540,2663,48,2017-2018
3,3,TOR,1995,500,2807,7169,0.472,3383,1790,0.794,...,2705,0.358,968,3607,1095,4464,0.541,2415,59,2017-2018
4,4,CLE,1916,312,2761,6950,0.476,3311,1909,0.779,...,2636,0.372,981,3455,1126,4314,0.540,2330,50,2017-2018

In [3]:
from sportsreference.nba.teams import Teams
teams = Teams("2017")

stats_16_17 = teams.dataframes

stats_16_17.head()

,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,...,rank,steals,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals
GSW,GSW,2491,555,2873,7140,0.495,3532,1850,0.788,1457,...,1,785,2562,0.383,982,3643,1211,4578,0.557,2550
HOU,HOU,2070,352,2746,7152,0.462,3305,2177,0.766,1667,...,2,670,3306,0.357,1181,3638,1240,3846,0.552,2124
DEN,DEN,2077,323,2837,7194,0.469,3377,1986,0.774,1537,...,3,568,2365,0.368,870,3803,1226,4829,0.519,2507
CLE,CLE,1858,327,2821,6963,0.470,3275,1913,0.748,1431,...,4,539,2779,0.384,1067,3587,1121,4184,0.528,2208
WAS,WAS,1956,336,2671,7137,0.475,3388,1812,0.784,1421,...,5,693,2030,0.372,756,3514,1162,5107,0.515,2632

In [4]:
wins_16_17 = pd.read_csv('team_wins_16_17.csv')
wins_16_17.head()

  abbreviation   W
0          BOS  53
1          CLE  51
2          TOR  51
3          WAS  49
4          ATL  43

In [5]:
stats_16_17 = stats_16_17.merge(wins_16_17, left_on='abbreviation', right_on='abbreviation')
stats_16_17 = stats_16_17.assign(Season=['2016-2017'] * 30)
stats_16_17.head()

,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,...,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals,W,Season
0,GSW,2491,555,2873,7140,0.495,3532,1850,0.788,1457,...,2562,0.383,982,3643,1211,4578,0.557,2550,67,2016-2017
1,HOU,2070,352,2746,7152,0.462,3305,2177,0.766,1667,...,3306,0.357,1181,3638,1240,3846,0.552,2124,55,2016-2017
2,DEN,2077,323,2837,7194,0.469,3377,1986,0.774,1537,...,2365,0.368,870,3803,1226,4829,0.519,2507,40,2016-2017
3,CLE,1858,327,2821,6963,0.470,3275,1913,0.748,1431,...,2779,0.384,1067,3587,1121,4184,0.528,2208,51,2016-2017
4,WAS,1956,336,2671,7137,0.475,3388,1812,0.784,1421,...,2030,0.372,756,3514,1162,5107,0.515,2632,49,2016-2017

In [6]:

all_df = pd.read_csv("total_stats.csv")
all_df = [all_df,stats_16_17]

all_df = pd.concat(all_df).reset_index(drop=True)

all_df = all_df.drop(columns= 'Unnamed: 0')

all_df

,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,...,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals,W,Season
0,GSW,2402,612,2877,6981,0.503,3509,1668,0.815,1360,...,2370,0.391,926,3568,1267,4611,0.560,2583,58,2017-2018
1,HOU,1767,392,2825,6906,0.460,3174,2061,0.781,1609,...,3470,0.362,1256,3564,1135,3436,0.558,1918,65,2017-2018
2,NOP,2195,485,2924,7241,0.483,3500,1716,0.772,1324,...,2312,0.362,837,3636,1223,4929,0.540,2663,48,2017-2018
3,TOR,1995,500,2807,7169,0.472,3383,1790,0.794,1422,...,2705,0.358,968,3607,1095,4464,0.541,2415,59,2017-2018
4,CLE,1916,312,2761,6950,0.476,3311,1909,0.779,1488,...,2636,0.372,981,3455,1126,4314,0.540,2330,50,2017-2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,DET,1732,310,2838,7282,0.449,3269,1586,0.719,1140,...,1915,0.330,631,3746,973,5367,0.492,2638,37,2016-2017
116,ORL,1820,396,2734,7133,0.440,3139,1753,0.747,1309,...,2139,0.328,701,3541,1091,4994,0.488,2438,29,2016-2017
117,UTA,1651,410,2774,6515,0.466,3033,1875,0.747,1401,...,2128,0.372,791,3545,1118,4387,0.511,2242,51,2016-2017
118,MEM,1744,344,2621,6854,0.435,2984,1918,0.784,1504,...,2169,0.354,767,3507,1059,4685,0.473,2217,43,2016-2017
119,DAL,1705,307,2516,6750,0.440,2968,1516,0.801,1215,...,2473,0.355,878,3163,972,4277,0.489,2090,33,2016-2017

In [7]:
X = all_df[["abbreviation","Season","assists", 'defensive_rebounds','field_goal_percentage','field_goals','opp_assists',
                        'opp_blocks','opp_defensive_rebounds', 'opp_field_goal_percentage','opp_points',
                        'opp_three_point_field_goal_percentage','opp_total_rebounds','opp_two_point_field_goal_percentage',
                        'points', 'three_point_field_goal_percentage', 'total_rebounds','two_point_field_goal_percentage']].set_index(['abbreviation', 'Season'])
y = all_df["W"].values.reshape(-1, 1)
print(X.shape, y.shape)

(120, 16) (120, 1)

In [8]:
# Use train_test_split to create training and testing data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [9]:
# Create a LinearRegression and adding 16-17

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions = predictions.flatten()


MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)

print(f"MSE: {MSE}, R2: {r2}")


lin_reg = pd.DataFrame({"Prediction": np.round(predictions , 2), "Actual": y_test.ravel()})

X_test.reset_index(inplace = True)

df_out = pd.merge(X_test, lin_reg, how = 'left',left_index = True, right_index = True)

df_out = df_out.loc[:,['Season', 'abbreviation', 'Prediction', 'Actual']]
df_out

MSE: 15.496433804915286, R2: 0.8983944047643683

       Season abbreviation  Prediction  Actual
0   2016-2017          PHO       29.13      24
1   2017-2018          DET       40.53      39
2   2017-2018          POR       47.11      49
3   2018-2019          MEM       33.90      33
4   2017-2018          MIN       47.92      47
5   2016-2017          LAC       54.61      51
6   2018-2019          BRK       42.42      42
7   2016-2017          WAS       46.14      49
8   2017-2018          PHI       52.07      52
9   2018-2019          DAL       38.43      33
10  2016-2017          GSW       73.14      67
11  2017-2018          NYK       33.89      29
12  2017-2018          SAC       22.17      27
13  2016-2017          CLE       48.29      51
14  2017-2018          PHO       16.46      21
15  2019-2020          OKC       39.02      40
16  2017-2018          UTA       48.26      48
17  2017-2018          DAL       31.84      24
18  2019-2020          BRK       30.84      30
19  2016-2017          MIN       38.64      31
20  2017-2018          NOP       46.33      48
21  2019-2020          CHO       15.67      23
22  2018-2019          POR       53.50      53
23  2018-2019          UTA       52.86      50
24  2019-2020          NOP       32.31      28
25  2019-2020          MIA       40.24      41
26  2017-2018          GSW       57.54      58
27  2016-2017          LAL       24.27      26
28  2019-2020          CLE       14.04      19
29  2018-2019          NOP       38.79      33

In [10]:
# trying to predict unseen data
new_df = pd.read_csv("new_stats.csv")

teams = Teams("2020")

stats_19_20 = teams.dataframes

wins_19_20 = pd.read_csv('../team_wins_19_20.csv')  

stats_19_20 = stats_19_20.merge(wins_19_20, left_on='abbreviation', right_on='abbreviation')
stats_19_20 = stats_19_20.assign(Season=['2019-2020'] * 30)

stats_19_20.head()

,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,...,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals,W,Season
0,DAL,1640,334,2438,6027,0.462,2787,1548,0.773,1196,...,2779,0.369,1026,3150,857,3248,0.542,1761,40,2019-2020
1,MIL,1685,390,2745,5928,0.477,2830,1562,0.742,1159,...,2510,0.356,893,3362,969,3418,0.567,1937,53,2019-2020
2,HOU,1375,329,2212,5803,0.454,2632,1664,0.787,1310,...,2832,0.348,986,2875,939,2971,0.554,1646,40,2019-2020
3,POR,1333,411,2335,5998,0.461,2763,1434,0.798,1145,...,2228,0.372,829,3001,858,3770,0.513,1934,29,2019-2020
4,ATL,1605,341,2237,6067,0.449,2723,1566,0.790,1237,...,2416,0.333,805,2898,1086,3651,0.525,1918,20,2019-2020

In [11]:
X = new_df[["abbreviation","Season","assists", 'defensive_rebounds','field_goal_percentage','field_goals','opp_assists',
                        'opp_blocks','opp_defensive_rebounds', 'opp_field_goal_percentage','opp_points',
                        'opp_three_point_field_goal_percentage','opp_total_rebounds','opp_two_point_field_goal_percentage',
                        'points', 'three_point_field_goal_percentage', 'total_rebounds','two_point_field_goal_percentage']].set_index(['abbreviation', 'Season'])
y = new_df["W"].values.reshape(-1, 1)
print(X.shape, y.shape)

(90, 16) (90, 1)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [15]:
#prediction of 16-19
model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions = predictions.flatten()


MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)

print(f"MSE: {MSE}, R2: {r2}")


lin_reg = pd.DataFrame({"Prediction": np.round(predictions , 2), "Actual": y_test.ravel()})

X_test.reset_index(inplace = True)

df_out = pd.merge(X_test, lin_reg, how = 'left',left_index = True, right_index = True)

df_out = df_out.loc[:,['Season', 'abbreviation', 'Prediction', 'Actual']]
df_out

MSE: 11.378464933737842, R2: 0.9028784053513083

       Season abbreviation  Prediction  Actual
0   2016-2017          NYK       33.92      31
1   2017-2018          PHI       51.55      52
2   2016-2017          CHI       41.47      41
3   2018-2019          SAC       36.65      39
4   2016-2017          MIN       39.94      31
5   2016-2017          SAC       34.30      32
6   2017-2018          OKC       47.10      48
7   2016-2017          LAC       53.07      51
8   2017-2018          MEM       27.68      22
9   2018-2019          ORL       40.96      42
10  2016-2017          HOU       54.78      55
11  2018-2019          PHI       47.11      51
12  2016-2017          NOP       32.69      34
13  2018-2019          ATL       25.25      29
14  2017-2018          DEN       43.40      46
15  2018-2019          CLE       18.44      19
16  2018-2019          OKC       45.50      49
17  2018-2019          DET       40.27      41
18  2018-2019          IND       50.42      48
19  2017-2018          CHI       20.66      27
20  2017-2018          ORL       29.73      25
21  2018-2019          HOU       54.75      53
22  2016-2017          CLE       49.82      51

In [16]:
#prediction 16-20 with 19-20 being unseen data
model = LinearRegression()
model.fit(X, y)

new_input = stats_19_20[["abbreviation","Season","assists", 'defensive_rebounds','field_goal_percentage','field_goals','opp_assists',
                        'opp_blocks','opp_defensive_rebounds', 'opp_field_goal_percentage','opp_points',
                        'opp_three_point_field_goal_percentage','opp_total_rebounds','opp_two_point_field_goal_percentage',
                        'points', 'three_point_field_goal_percentage', 'total_rebounds','two_point_field_goal_percentage']].set_index(['abbreviation', 'Season'])

new_actual = stats_19_20["W"].values.reshape(-1, 1)

predictions = model.predict(new_input)
predictions = predictions.flatten()


MSE = mean_squared_error(new_actual, predictions)
r2 = model.score(new_input, new_actual)

print(f"MSE: {MSE}, R2: {r2}")


lin_reg2 = pd.DataFrame({"Prediction": np.round(predictions , 2), "Actual": new_actual.ravel()})

new_input.reset_index(inplace = True)

df_out = pd.merge(new_input, lin_reg2, how = 'left',left_index = True, right_index = True)

df_out = df_out.loc[:,['Season', 'abbreviation', 'Prediction', 'Actual']]
df_out

MSE: 98.50209406323485, R2: 0.0621726173247219

       Season abbreviation  Prediction  Actual
0   2019-2020          DAL       54.22      40
1   2019-2020          MIL       61.84      53
2   2019-2020          HOU       50.03      40
3   2019-2020          POR       38.84      29
4   2019-2020          ATL       26.52      20
5   2019-2020          NOP       41.37      28
6   2019-2020          LAC       54.64      44
7   2019-2020          WAS       33.17      24
8   2019-2020          MEM       39.17      32
9   2019-2020          PHO       37.67      26
10  2019-2020          MIA       49.88      41
11  2019-2020          MIN       32.61      19
12  2019-2020          BOS       54.81      43
13  2019-2020          TOR       54.66      46
14  2019-2020          LAL       56.79      49
15  2019-2020          DEN       48.24      43
16  2019-2020          SAS       37.85      27
17  2019-2020          PHI       46.61      39
18  2019-2020          IND       47.00      39
19  2019-2020          UTA       50.69      41
20  2019-2020          OKC       48.64      40
21  2019-2020          BRK       40.08      30
22  2019-2020          DET       36.23      20
23  2019-2020          NYK       26.28      21
24  2019-2020          SAC       40.10      28
25  2019-2020          CLE       27.54      19
26  2019-2020          CHI       36.02      22
27  2019-2020          ORL       36.48      30
28  2019-2020          GSW       19.93      15
29  2019-2020          CHO       27.66      23